- name: Demo on variables
  hosts: all
  vars:
    URL: variable.example.com
  tasks:
    - name: Print URL
      ansible.builtin.debug:
        msg: URL = {{ URL }}

- name: Demo on file variables
  hosts: all
  vars_files:
    - sample-vars.yml
  tasks:
    - name: Print URL
      ansible.builtin.debug:
        msg: URL = {{URL}}
- name: Task level variables
  hosts: all
  tasks:
    - name: Print URL Task level
      ansible.builtin.debug:
        msg: URL = {{ URL }} , Phone = {{ Phone }}
      vars:
        URL: Task.example.com
        Phone: 9493997576
- name: variables from inventory files
  hosts: all
  tasks:
    - name: print URL
      ansible.builtin.debug:
        msg: URL == {{ URL }}
- name: Pre-defined arguments example
  hosts: all
  tasks:
    ansible.builtin.debug:
      msg: Hostname = {{ ansible_hostname }}