- name: Demo on variables
  hosts: all
  vars:
    URL: variable.example.com
  tasks:
    - name: Print URL
      ansible.builtin.debug:
        msg: URL = {{ URL }}

- name: Demo on file variables
  hosts: all
  vars_file:
    - sample-vars.yml
  tasks:
    - name: Print URL
      ansible.builtin.debug:
        msg = {{URL}}